### PR TITLE
Sync indigo devel mar 2018

### PR DESCRIPTION
**Pull request by sjfwilson**
Sync to head of ros/actionlib indigo-devel

I have included people in the reviewer list based on past and present interest in ActionLib and ActionLib accessories. Mostly this is an FYI: You may be interested in what is coming in.

This fork maintains the LOST goal hack I put in nearly 2 years ago. We believe we can remove this hack once DDS is fully integrated into our product.

### CODE REVIEW

**Review by efernandez — APPROVED** [review]
Have we tested this already somehow?

**Comment by sjfwilson** [comment]
@efernandez Yes, it has been tested in a test bed with 30 fake robots, with CISIM, and on the floor with 5 robots.

**Comment by jasonimercer** [comment]
I feel like this is either unreviewable or we are not in a position where we have the ability to make changes. It's good to see that things are changing but with all the bad style changes (in polite discussion with the author of the style change here: https://github.com/ros/actionlib/pull/72 ) I can't see at a glance what's real change and what's window dressing. Perhaps the best way forward is to work through the commits listed one-by-one? I'll give that a shot.

**Comment by jasonimercer** [comment]
94649d7 was a bad commit. Assert needs to be before lock.

**Comment by jasonimercer** [comment]
OK, aside from the commit where we lock on a member of a object before we check to see that we have a valid pointer to the object and the cringe-worthy style that is the ROS 2 style, the rest of the commits look good. We should make a commit that fixes 94649d7 and give it to upstream.

**Review by jasonimercer — APPROVED** [review]

**Comment by sjfwilson** [comment]
@jasonimercer Good find regarding [94649d7](https://github.com/clearpathrobotics/actionlib/commit/94649d74320196ff6e8d8a353101808f31bf68cf).

Did you want this addressed upstream before we merge into our fork? Or are we okay merging at risk, and getting the upstream fix in place in parallel?

**Comment by jasonimercer** [comment]
probably easiest to merge now - it's more of a theoretical issue since the assert never triggered in the past anyway. Either way if the pointer is a nullptr then the process is coming down.

I'm OK with a fix + upstream PR after your sync is done.

**Pull request merged**
